CC = gcc
CFLAGS = -g
LDFLAGS = -lm
OBJS = encrypt.o decrypt.o message_hider.o

all: message_hider

message_hider: $(OBJS)
	$(CC) $(LDFLAGS) encrypt.o decrypt.o message_hider.o -o message_hider

message_hider.o: message_hider.c decrypt.h encrypt.h
	$(CC) $(CFLAGS) -c message_hider.c -o message_hider.o

decrypt.o: decrypt.c decrypt.h encrypt.h
	$(CC) $(CFLAGS) -c decrypt.c -o decrypt.o

encrypt.o: encrypt.c encrypt.h
	$(CC) $(CFLAGS) -c encrypt.c -o encrypt.o
